sudo: required
services:
  - docker

env:
  global:
    - secure: "MHqUC3cGAy9bAmTsIPXEOBwkP7hqYeG429Z/8Pno689QfbHS0uWDIsP97aoApsirX4yHGnINuIbgX6TkapAjpRko1Mow6bQmnE5cZJW5etaHIzNFvcGBJwbpueXBRQWlijw69ZGF8NMVkAMFJfthFGFipl0zSfefsrpb1oxX2ETVrWdsA80WMOZzJVv4ay5DV6td/A3yBjDZshl4t4kGk4sxqtE8QHIzucImU0X9xQdnLBW2o0eqTNTr9ZkNSfDJgBHk6NMd4oubT1pbA3Dq4uCbxJLw3V8gSTfvKqIvX944RB3oCAruDN39LgbszWYfaaXBwarEERob4hJjn/3dIuRBiSSolQZMEYpzJcQ5Vs4ZZIP0ZhWh5c+5f2zAF7pxi4ddv9Bd8BVhcgOF095EiyprOIPA7glpyktOgldv8lKtN09NiMNHpFOa54aDrvofqQIK5E7xPkdu3v9nAk7E1uM8sOQ7hb8RnwvS8qeK8nWT9JyM8cAWCJFrSo1MOH4lvTNUxV/Uc06FPK8Np6RlfQo4IX+0Hvs1P4jp8feKmBIOSlxrMXJoV8GBn+Ugj/SCp8H2L2jL47Iln6wnDb+/QzpjFaODAgtTClz6A2qQHPW2Q3Rj8TjhIfdQDAZakMocCK6HJRJZGl3YHb4RM7mTkSqMw9/NulZJN9KF6egjHWQ="
    - secure: "jUcBkgKyMs3CKYPsS8AuQNmt4axtKWKyHI8rB14Bm63SnuPv/SCp+ySqafu/908RoseJBN6tyWAjVS8BQNZdHVVq2dh2rcjWLN43rXQKhiw2G5o+sVVtgk4Ip3OY4AX+O3WtQss5Y+5bijmZkI9IH1GOiIjmkBSSGfI4qG0yqjjeBobH93NnTXvjJeFu0P3lT3bdemfgGSVaownNL3GZ1qkhDdlTKtHMqYnLpPP9RnCda4AR/0sBp2HBlJY0+Fr+jZQpRYjstsJyeqEG8dlW8Vf8VGoZnWglhjBZhp5BAu/fa8y3rr7RYUm/OvHUWHicdWUDy41XZTFlXGkXql+WqX35gJwq1s7FP/JS8ZUwo3ujdEnHHN4xwgya/hnAdRYVu1Aw1wOrJIgdDOFXW13CNL4G+d2BU13UUE/DfEKvE8O+frgACtIcQ46xxfmlG2AMlXhYwCNKkk3jTyOxdtfszGYfQibFEUe5qI5Eioo5OcPYUww4DB1Dow2xgGSrIrWKeNLInZWqnWRkJx92wdWQVFeYI5alrILtm+JUG/MuK1e8kfT163ApK831NhdCaXBEKJJ0FhTBtnr+44joAJJrScudzTKEz8ohOW0WPxBFGRSzB76aehrBwwgZlu4Ka5/gteoKcZCiZUAH98TZF3AIZcMW5/WKjLsVgJEY43dpXzU="

script:
  - make image
  - IMGTAG=travis-${TRAVIS_BUILD_ID} make tag-image
  - IMGTAG=latest make tag-image
  - make docker-login 
  - make push-image