sudo: required
services:
  - docker

env:
  global:
    - secure: "MHqUC3cGAy9bAmTsIPXEOBwkP7hqYeG429Z/8Pno689QfbHS0uWDIsP97aoApsirX4yHGnINuIbgX6TkapAjpRko1Mow6bQmnE5cZJW5etaHIzNFvcGBJwbpueXBRQWlijw69ZGF8NMVkAMFJfthFGFipl0zSfefsrpb1oxX2ETVrWdsA80WMOZzJVv4ay5DV6td/A3yBjDZshl4t4kGk4sxqtE8QHIzucImU0X9xQdnLBW2o0eqTNTr9ZkNSfDJgBHk6NMd4oubT1pbA3Dq4uCbxJLw3V8gSTfvKqIvX944RB3oCAruDN39LgbszWYfaaXBwarEERob4hJjn/3dIuRBiSSolQZMEYpzJcQ5Vs4ZZIP0ZhWh5c+5f2zAF7pxi4ddv9Bd8BVhcgOF095EiyprOIPA7glpyktOgldv8lKtN09NiMNHpFOa54aDrvofqQIK5E7xPkdu3v9nAk7E1uM8sOQ7hb8RnwvS8qeK8nWT9JyM8cAWCJFrSo1MOH4lvTNUxV/Uc06FPK8Np6RlfQo4IX+0Hvs1P4jp8feKmBIOSlxrMXJoV8GBn+Ugj/SCp8H2L2jL47Iln6wnDb+/QzpjFaODAgtTClz6A2qQHPW2Q3Rj8TjhIfdQDAZakMocCK6HJRJZGl3YHb4RM7mTkSqMw9/NulZJN9KF6egjHWQ="
    - secure: "AVs0DQnBHLiyx378TuadCbdRhRPHLjS7bqqU9UH7WzMYIj0gDkb9v/AAAhrVoViIHkgnk5dvzgqpC3Ldq4xOJrcb7etNFNtmSCT5A4KeFqo3Rlli8wLz077DE5WtYRzj4OsBnUILYk/3u7uPvxDUqZjlk04SpkyK+Fx7/OnDX0YDG9z1Fh8zba0wUDvqUVTqq4f9T3UrRzSinRLN4rvAbi/oUdKyRfayFIH/CJ2GpoullUw4rVVC7A0ZyPQrWyZurvmsOLzOEG4UWaOPOvUSwhZ1d16d42KIMiMJU1BbWiIW1vs8pFN+ZxIrhohuIZ3qNbCCYJgfbtz7dVVkxPYtIYx1x/Zt09aGORWQlvpqWBi7AqyCuD+Amjli7fHnFuWu9+lg9EJQg6/HBNjLJEIsbeFfEJCq5YogPpLT8oZ/HtELOCSU9sH6CjVfa7MKKc+df/GWXBSZIVEn6U2Bf4Ydm6KE+z/SGHJ21AMqKt9L5CCrlpicD/ZTWKcYwVTKL/izVVOpcP00NQ2SvYjP7DrXHMIRZsXKVM2QtRvfhoa9zWZzl2foU6W7vU3olnb+P+WiJf3jEZk+095fxGVIXGCI2VJ6/k7QLCsHCw1VL6owpfWLuy+M7uqh4wwAsJwq1JGshlyzNDlvVzvYnhAvvwHnN9rakqX73HZvXsnOhxJMAco="

script:
  - make image
  - IMGTAG=travis-${TRAVIS_BUILD_ID} make tag-image
  - IMGTAG=latest make tag-image
  - make docker-login 
  - make push-image